### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by GhaniaH**

### CODE REVIEW

**Comment by vvo** [comment]
Hey hi, what is your intent in submitting this PR? What are you solving? Thanks!

**Comment by GhaniaH** [comment]
Hi,
it's a master programming project, so i have to do modifications about
insert-css.

**Comment by vvo** [comment]
I am sorry I am not sure this is sufficient or really required. I understand it's part of your studies but it needs to be more thought:
- linting and formatting is only valuable when automatized
- prettier is a good way to automatically format the code (with precommit hook, follow readme)
- travis should be setup so that eslint is ran on pull requests
- you should provide an eslint config

**Comment by substack** [comment]
This package is really tiny, I don't think it needs any of that.

**Comment by vvo** [comment]
@GhaniaH I am sure there are better projects that could be benefiting from your work (aside from changing package.json and adding eslint). Good luck.

**Pull request closed without merging**
