### PR TITLE
Add named export

### PR DESCRIPTION
**Pull request by jonaskello**

### CODE REVIEW

**Comment by jonaskello** [comment]
This PR should not break anything existing, it just adds a named export. With this PR it will be possible in ES6 syntax and in typescript to use either:

```js
import insertCss from "insert-css";
```

or

```js
import {insertCss} from "insert-css";
```

**Comment by vvo** [comment]
But why would you want to use "import {insertCss} from "insert-css";" ?

**Comment by vvo** [comment]
Can you add some reference issues/discussions saying that module.export = function() {} is not working in typescript

**Comment by jonaskello** [comment]
Here is one example [comment](https://github.com/Microsoft/TypeScript/issues/2719#issuecomment-92189669) from the typescript language designer:

> This is the one big difference between default exports in ES6 and assigning to module.exports in CommonJS. There is really no clean way to solve this problem. Babel supports a compatibility mode and a magic __esModule marker that you dynamically have to check, but I'm not convinced that's any better. My feeling is we're better off just going with pure ES6 semantics.

**Comment by jonaskello** [comment]
You can make importing of commonjs default exports work in some circumstances. For example there is a special syntax introduced to solve this. You can look at [this page](https://www.typescriptlang.org/docs/handbook/modules.html) under the heading "export = and import = require()". The syntax looks like `import foo = require("foo")` which is a specifc typescript syntax to solve this problem. However that syntax is only available if you target es5 as output and that is not possible if you for example have generator functions. In that case you need to target es6 and then compile with babel to es5 and in this case you cannot use the special import syntax.

**Comment by vvo** [comment]
If I understand well, this can be solved on your side if you use:

```js
import insertCSS = require("insert-css")
```

?

If so then why not use it? There are millions of npm modules right now that would need the "fix" otherwise. Why would this module be "fixed" and not the others.

For sure it's very easy for us to accept the pull request, I just think that the current solution you propose is not future proof.

There's no magical solution, let's say the module was written in full ES6, people using commonJS would have to do:

```js
var insertCSS = require('insert-css').default
```

Which is not optimal neither.

To me, those module issues can be solved by module bundlers/tooling, not from the code. This is a commonJS module for now. Can be turned into an ES module and add some tooling to build it in a way that works everywhere maybe, I would prefer that, even if that's more work.

The first thing you would notice on the codebase is the double export, then you would ask yourself "WHY?". Even if you add a comment like "This is for TypeScript". This has no end, then we will have "This is for Babel" "This is for flow"..

The state of modules in the JavaScript world is currently messy, but I don't feel like adding named exports everywhere in commonJS modules is a solution either.

I hope you understand. I am open to PRs that will not mix exports just for the sake of some module bundler to work. Either it's written in ES form, or in commonJS form and then the tooling/bundling is doing what needs to be done.

**Comment by jonaskello** [comment]
No this could not be solved on my end by using `import insertCSS = require("insert-css")` becuase that option is not compatible with the typescript compiler option to output es6 which is a requirement for my workflow. If I use that syntax the compiler throws an error saying it is not possible. Plese read my comment above where I already explained this.

I totally agree with you that this feels like something that should be solved by bunders, compilers etc. And I really, really wish that could be done. But having tried for the longsest time to make all tools work together I have realised that it simply is not possible. Also when the person that designed both the C# language and typescript langauge says there is no solution I finally took his word for it and gave up. Here is antoher [issue](https://github.com/Microsoft/TypeScript/issues/5565#issuecomment-155226290) where he recommends hacking the original library (there are tons of these issues around default exports if you just search for them):

>So, instead of using the modified declaration file you could fix redux-logger yourself by deleting the last line in node_modules/redux-logger/lib/index.js

The way I see it is that there are incompabilities between the module formats, compilers and bundlers regarding the default exports. Named exports however in my experience always works in all situations regardless of the workflow. So to provide your exports both as a default export and a named export is IMO not a "fix" but a best practice to maximize the compability with all workflows and module formats. Your example above with incompability between es6 and commonjs could also be solved by a named export.

Another reason I did the PR is that I believe that the best ways to solve things in open source is to work togheter so as many ppl as possible can use the code. But I totally respect that maximizing compability to cover advanced worksflows and module format interopability is not a priority of this project. So for this reason the only solution I am left with is to fork this project and make a new npm pacakge. Please note that at this point this is my **only** option. I would not do it if I could see any other solution as I think there are enough packges on npm that do the same thing already.

**Comment by jonaskello** [comment]
Btw, the reason other packages does not need to be "fixed" is that they already provide a named export :-). For example have a look at [csjs](https://github.com/rtsao/csjs), which exports the same thing both as default and named `csjs`. Or look at the `from` export in in [seamless-immutable](https://github.com/rtfeldman/seamless-immutable) which is exactly the same as the default export.

**Comment by vvo** [comment]
Hi @jonaskello

**Comment by vvo** [comment]
Thanks for the complete explanation and sorry to have been a bit defensive here. Ultimately this module nightmare will be solved. Can I let you do the release also? Thanks

**Comment by vvo** [comment]
> Another reason I did the PR is that I believe that the best ways to solve things in open source is to work togheter so as many ppl as possible can use the code

:+1:

**Comment by jonaskello** [comment]
Thank you! To have high quality open source packages it is of course important for maintainers to throughly review all PR so I totally understand your stance here. Sorry for being a bit adamant about this issue but I really felt I was out of options. Trying to get all tools to work together can be a bit frustrating at times. If I find a way to solve the issue in the tools I will let you know but as I said I don't have much hope of that at this point. Hopefully in a not too distant future the whole JS community will move to ECMA standard module format.

>Can I let you do the release also? 

I think I could publish to npm but I don't think I can update package.json, make a tag and github release? Should I make a PR to update the version in package.json and maybe add a note to the README? Would you prefer 1.0.1 or 1.1.0?

**Comment by vvo** [comment]
1.1.0 should do it, only updating package.json should do it. I asked @substack to add you as a maintainer to ease the process but no luck

**Pull request merged**
